# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '网络解析' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire', '~> 4.6.0'
  # Pods for 网络解析

end
